name: Build CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    environment: Production

    strategy:
      matrix:
        node: [20.x]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Using Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
